routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return redirect()->route('get.login');
});

Route::get('/login', [
    'uses' => 'Auth\LoginController@showLoginForm',
    'as' => 'get.login',
]);

Route::post('/login', [
    'uses' => 'Auth\LoginController@login',
    'as' => 'post.login',
]);

Route::post('/logout', [
    'uses' => 'Auth\LoginController@logout',
    'as' => 'post.logout',
]);

Route::get('/student-application', [
    'uses' => 'HomeController@studentApplication',
    'as' => 'get.student-application',
]);

Route::post('/student-application', [
    'uses' => 'HomeController@submitstudentApplication',
    'as' => 'post.student-application',
]);

Route::group(['middleware' => 'auth', 'prefix' => 'dashboard'], function () {
    Route::get('/', [
        'uses' => 'HomeController@index',
        'as' => 'get.home',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'admission', 'middleware' => ['role:Super Admin|Admission Staff']], function () {

    Route::get('/', [
        'uses' => 'AdmissionController@index',
        'as' => 'get.admission',
    ]);

    Route::get('/list-of-student', [
        'uses' => 'AdmissionController@oldstud',
        'as' => 'get.admission.oldstud',
    ]);

    Route::post('/unverified-student-delete', [
        'uses' => 'AdmissionController@deleteUnverified',
        'as' => 'post.admission.student-delete',
    ]);

    Route::post('/manual-addStudent', [
        'uses' => 'AdmissionController@manualAddStudent',
        'as' => 'post.manual.add-student',
    ]);

    Route::get('/unverified-student', [
        'uses' => 'AdmissionController@unverifiedStudent',
        'as' => 'get.admission.unverified-student',
    ]);

    Route::get('/get-unverified-student', [
        'uses' => 'AdmissionController@getUnverifiedStudent',
        'as' => 'get.admission.unverified-student.details',
    ]);

    Route::post('/verify-unverified-student', [
        'uses' => 'AdmissionController@verifyStudent',
        'as' => 'post.admission.verify-student',
    ]);

    Route::get('/rooms', [
        'uses' => 'AdmissionController@roomShow',
        'as' => 'get.admission.rooms',
    ]);

    Route::post('create/room', [
        'uses' => 'AdmissionController@createRoom',
        'as' => 'get.create.admission.rooms',
    ]);

    Route::post('edit/room', [
        'uses' => 'AdmissionController@editRoom',
        'as' => 'get.edit.admission.rooms',
    ]);

    Route::get('edit/room', [
        'uses' => 'AdmissionController@getRoom',
        'as' => 'get.admission.rooms.details',
    ]);

    Route::post('delete/room', [
        'uses' => 'AdmissionController@deleteRoom',
        'as' => 'get.delete.rooms.details',
    ]);

    Route::get('/subjects', [
        'uses' => 'AdmissionController@subjectShow',
        'as' => 'get.admission.subjects',
    ]);

    Route::post('create/subjects', [
        'uses' => 'AdmissionController@createSubjects',
        'as' => 'get.create.admission.subjects',
    ]);

    Route::post('edit/subjects', [
        'uses' => 'AdmissionController@editSubjects',
        'as' => 'get.edit.admission.subjects',
    ]);

    Route::get('edit/subjects', [
        'uses' => 'AdmissionController@getSubjects',
        'as' => 'get.admission.subjects.details',
    ]);

    Route::post('delete/subjects', [
        'uses' => 'AdmissionController@deleteSubjects',
        'as' => 'get.delete.subjects.details',
    ]);

    Route::get('/sections', [
        'uses' => 'AdmissionController@sectionShow',
        'as' => 'get.admission.sections',
    ]);

    Route::get('get/sections', [
        'uses' => 'AdmissionController@getSection',
        'as' => 'get.admission.det.sections',
    ]);

    Route::post('/add/sections', [
        'uses' => 'AdmissionController@sectionAdd',
        'as' => 'get.admission.add.sections',
    ]);

    Route::post('/edit/sections', [
        'uses' => 'AdmissionController@sectionEdit',
        'as' => 'get.admission.edit.sections',
    ]);

    Route::post('/delete/sections', [
        'uses' => 'AdmissionController@sectionDelete',
        'as' => 'get.admission.del.sections',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => '', 'middleware' => ['role:Super Admin|Registrar Staff']], function () {

    Route::get('/request-forms', [
        'uses' => 'ScheduleController@requestForms',
        'as' => 'get.request-forms',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'schedules', 'middleware' => ['role:Super Admin|Registrar Staff']], function () {

    Route::get('/', [
        'uses' => 'ScheduleController@showSchedules',
        'as' => 'get.schedules',
    ]);

    Route::post('/', [
        'uses' => 'ScheduleController@addSchedule',
        'as' => 'get.schedules.add',
    ]);

    Route::post('/edit', [
        'uses' => 'ScheduleController@editSchedule',
        'as' => 'get.schedules.update',
    ]);

    Route::get('/get', [
        'uses' => 'ScheduleController@getSchedule',
        'as' => 'get.schedules.edit',
    ]);

    Route::post('/delete', [
        'uses' => 'ScheduleController@deleteSchedule',
        'as' => 'get.schedules.delete',
    ]);
});

Route::group(['middleware' => 'auth', 'prefix' => 'enrollment', 'middleware' => ['role:Super Admin|Registrar Staff']], function () {

    Route::get('/', [
        'uses' => 'EnrollmentController@showEnrollment',
        'as' => 'get.enrollment',
    ]);

    Route::get('/section/{id}/show', [
        'uses' => 'EnrollmentController@viewSection',
        'as' => 'get.students.enrollment',
    ]);

    Route::post('/enroll', [
        'uses' => 'EnrollmentController@enrollStudent',
        'as' => 'post.enroll.student',
    ]);

    Route::post('/remove-student', [
        'uses' => 'EnrollmentController@removeStudentFromSection',
        'as' => 'post.remove.student',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'user-management', 'middleware' => ['role:Super Admin']], function () {

    Route::get('/', [
        'uses' => 'UserController@index',
        'as' => 'get.user-management',
    ]);

    Route::post('/store', [
        'uses' => 'UserController@store',
        'as' => 'post.new-user',
    ]);

    Route::get('/list', [
        'uses' => 'UserController@show',
        'as' => 'get.user-by-role',
    ]);

    Route::post('/manage-roles', [
        'uses' => 'UserController@manageRole',
        'as' => 'post.manage-roles',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'guidance', 'middleware' => ['role:Super Admin|Guidance Staff']], function () {
    Route::resource('incident-report', 'GuidanceController');
});

Route::group(['middleware' => 'auth', 'prefix' => 'teacher', 'middleware' => ['role:Faculty']], function () {
    Route::get('/sections', [
        'uses' => 'TeacherController@sections',
        'as' => 'teacher.sections',
    ]);
    Route::get('/schedules', [
        'uses' => 'TeacherController@schedule',
        'as' => 'teacher.schedule',
    ]);
    Route::get('/section/{section}/grades', [
        'uses' => 'TeacherController@grades',
        'as' => 'teacher.grades',
    ]);
    Route::post('/grade-save', [
        'uses' => 'TeacherController@gradeSave',
        'as' => 'grade.save',
    ]);

    Route::get('/files', [
        'uses' => 'ClinicController@showFiles',
        'as' => 'clinic.files',
    ]);

    Route::post('/files', [
        'uses' => 'ClinicController@uploadFiles',
        'as' => 'get.file',
    ]);

    Route::post('/files/delete', [
        'uses' => 'ClinicController@delteFiles',
        'as' => 'get.delete',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'clinic', 'middleware' => ['role:Super Admin|Clinic Staff']], function () {
    Route::get('/', [
        'uses' => 'ClinicController@index',
        'as' => 'clinic.index',
    ]);

    Route::get('/logs', [
        'uses' => 'ClinicController@showLogs',
        'as' => 'clinic.logs',
    ]);

    Route::post('/logs', [
        'uses' => 'ClinicController@addLogs',
        'as' => 'get.log',
    ]);

    Route::get('/seminar', [
        'uses' => 'ClinicController@showSeminar',
        'as' => 'clinic.seminars',
    ]);

    Route::post('/logs', [
        'uses' => 'ClinicController@addLogs',
        'as' => 'get.log',
    ]);

    Route::get('/deworming', [
        'uses' => 'ClinicController@showDeworming',
        'as' => 'clinic.deworming',
    ]);

    Route::get('/view/section/{id}', [
        'uses' => 'ClinicController@showStudents',
        'as' => 'clinic.view.section',
    ]);

    Route::post('/view/section', [
        'uses' => 'ClinicController@dewormStudent',
        'as' => 'post.deworm.student',
    ]);

    Route::get('/folic', [
        'uses' => 'ClinicController@showFolic',
        'as' => 'clinic.folic',
    ]);

    Route::get('/folic/section/{id}', [
        'uses' => 'ClinicController@showFolicStudents',
        'as' => 'clinic.folic.section',
    ]);

    Route::post('/folic/section', [
        'uses' => 'ClinicController@folicStudent',
        'as' => 'post.folic.student',
    ]);

    Route::get('/feeding', [
        'uses' => 'ClinicController@showFeeding',
        'as' => 'clinic.feeding',
    ]);

    Route::get('/feeding/section/{id}', [
        'uses' => 'ClinicController@showFeedingStudents',
        'as' => 'clinic.feeding.section',
    ]);

    Route::post('/feeding/section', [
        'uses' => 'ClinicController@feedingStudent',
        'as' => 'post.feeding.student',
    ]);

    Route::get('/nutritional', [
        'uses' => 'ClinicController@showNutritional',

resources/views/partials/dashboard/_footer.blade.php
<style type="text/css">
.capbox {
    background-color: #92D433;
    border: #B3E272 0px solid;
    border-width: 0px 12px 0px 0px;
    display: inline-block;
    *display: inline; zoom: 1; /* FOR IE7-8 */
    padding: 8px 40px 8px 8px;
    }

.capbox-inner {
    font: bold 11px arial, sans-serif;
    color: #000000;
    background-color: #DBF3BA;
    margin: 5px auto 0px auto;
    padding: 3px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
    }

#CaptchaDiv {
    font: bold 17px verdana, arial, sans-serif;
    font-style: italic;
    color: #000000;
    background-color: #FFFFFF;
    padding: 4px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
    }

#CaptchaInput { margin: 1px 0px 1px 0px; width: 135px; }

</style>
<footer class="footer text-center"> 2017 &copy; School Portal </footer>

resources/views/partials/dashboard/_head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
<title>School Portal</title>
<!-- Bootstrap Core CSS -->
<link href="{{ asset('pixeladmin/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
<!-- Menu CSS -->
<link href="{{ asset('plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css') }}" rel="stylesheet">
<!-- toast CSS -->
<link href="{{ asset('plugins/bower_components/toast-master/css/jquery.toast.css') }}" rel="stylesheet">
<!-- morris CSS -->
<link href="{{ asset('plugins/bower_components/morrisjs/morris.css') }}" rel="stylesheet">
<!-- animation CSS -->
<link href="{{ asset('pixeladmin/css/animate.css') }}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{{ asset('pixeladmin/css/style.css') }}" rel="stylesheet">

<link href="{{ asset('plugins/bootstrap_select/css/bootstrap-select.min.css') }}" rel="stylesheet">

<link href="{{ asset('pixeladmin/css/style.css') }}" rel="stylesheet">

<link href="{{ asset('plugins/datatable.css') }}" rel="stylesheet">
<!-- color CSS -->
<link href="{{ asset('pixeladmin/css/colors/blue-dark.css') }}" id="theme" rel="stylesheet">

resources/views/partials/dashboard/_javascript.blade.php
<script src="{{ asset('plugins/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{{ asset('pixeladmin/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Menu Plugin JavaScript -->
<script src="{{ asset('plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js') }}"></script>
<!--slimscroll JavaScript -->
<script src="{{ asset('pixeladmin/js/jquery.slimscroll.js') }}"></script>
<!--Wave Effects -->
<script src="{{ asset('pixeladmin/js/waves.js') }}"></script>
<!--Counter js -->
<script src="{{ asset('plugins/bower_components/waypoints/lib/jquery.waypoints.js') }}"></script>
<script src="{{ asset('plugins/bower_components/counterup/jquery.counterup.min.js') }}"></script>
<!--Morris JavaScript -->
<script src="{{ asset('plugins/bower_components/raphael/raphael-min.js') }}"></script>
<script src="{{ asset('plugins/bower_components/morrisjs/morris.js') }}"></script>
<script src="{{ asset('plugins/datatable.min.js') }}"></script>
<!-- Custom Theme JavaScript -->
<script src="{{ asset('pixeladmin/js/custom.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap_select/js/bootstrap-select.min.js') }}"></script>
<script src="{{ asset('plugins/bower_components/toast-master/js/jquery.toast.js') }}"></script>
<script src="https://unpkg.com/sweetalert2@7.1.2/dist/sweetalert2.all.js"></script>

resources/views/partials/dashboard/_nav.blade.php
<style type="text/css">
    .navbar-header {
    background: #5e0000;
}

#side-menu>li>a.active {
    border-left: 3px solid #5e0000;
    color: #ffffff;
    font-weight: 500;
}
.sidebar-nav  {
    background: #5e0000;

}
.fa  {
    color: white;
}

</style>
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse">
            <i class="fa fa-bars"></i>
        </a>
        <div class="top-left-part">
            <a class="logo" href="#">
                <b><img src="{{ asset('/plugins/images/pixeladmin-logo.png') }}" alt="home"/></b>
                <small class="hidden-xs">School<b> Portal</b></small>
            </a>
        </div>
        <ul class="nav navbar-top-links navbar-right pull-right">
            @if(Auth::user())
            <li>
                <a class="profile-pic" href="#">
                    <img src="{{ asset('') . auth()->user()->picture }}" alt="user-img" width="36" class="img-circle">
                    <b class="hidden-xs">{{ auth()->user()->first_name }}</b>
                </a>
            </li>
            @endif
        </ul>
    </div>
</nav>
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <ul class="nav" id="side-menu">
            @if(Auth::user())
            <li style="padding: 10px 0 0;">
                <a href="{{ route('get.home') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Dashboard</span></a>
            </li>
            @if(auth()->user()->hasRole(['Super Admin','Admission Staff']))
            <li>
                <a href="{{ route('get.admission') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Admission</span></a>
            </li>
            @endif
            @if(auth()->user()->hasRole(['Registrar Staff','Super Admin']))
            <li>
                <a href="{{ route('get.schedules') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Schedules</span></a>
            </li>
            <li>
                <a href="{{ route('get.enrollment') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Enrollment</span></a>
            </li>
            <li>
                <a href="{{ route('get.request-forms') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Request Forms</span></a>
            </li>
            @endif
            @if(auth()->user()->hasRole(['Guidance Staff','Super Admin']))
            <li>
                <a href="{{ route('incident-report.index') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Guidance</span></a>
            </li>
            @endif
            @if(auth()->user()->hasRole(['Clinic Staff','Super Admin']))
            <li>
                <a href="{{ route('clinic.index') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Clinic</span></a>
            </li>
            @endif
            @if(auth()->user()->hasRole(['Faculty']))


                     <li>
                <a href="{{ route('clinic.files') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Files</span></a>
            </li>
            <li>
                <a href="{{ route('teacher.sections') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Grades</span></a>
            </li>
            <li>
                <a href="{{ route('teacher.schedule') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Schedules</span></a>
            </li>
            @endif

            @if(auth()->user()->hasRole('Student'))
            <li>
                <a href="{{ route('student.schedules') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Schedules</span></a>
            </li>
             <li>
                <a href="{{ route('student.grades') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Grades</span></a>
            </li>
            <li>
                <a href="{{ route('student.fuckshit') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Request Form</span></a>
            </li>

                        <li>
                <a href="{{ route('get.profile') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Profile</span></a>
            </li>


                        <li>
                <a href="{{ route('student.asd') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Non-acad</span></a>
            </li>
            @endif


            @if(auth()->user()->hasRole('Super Admin'))
            <li>
                <a href="{{ route('get.user-management') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">User Management</span></a>
            </li>
            @endif
            <li>
                <a href="#" onclick="document.getElementById('form-logout').submit();"  class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Logout</span></a>
            </li>
            @endif
            @if(Auth::guest())
            <li style="padding: 10px 0 0;">
                <a href="{{ route('get.login') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Login</span></a>
            </li>
            <li>
                <a href="{{ route('get.student-application') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Student Application</span></a>
            </li>
                 <li>
                <a href="{{ route('student.fuckshit') }}" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Request Form</span></a>
            </li>
            @endif
        </ul>
        @if(Auth::user())
        <form id="form-logout" method="POST" action="{{ route('post.logout') }}">
            {{ csrf_field() }}
        </form>
        @endif
    </div>
</div>

resources/views/partials/dashboard/_preloader.blade.php
<div class="preloader">
    <div class="cssload-speeding-wheel"></div>
</div>